image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-authentication-and-member-microservice:
  stage: build
  script:
    gradle authentication-and-member-microservice:assemble authentication-and-member-microservice:testClasses

checkStyle-authentication-and-member-microservice:
  stage: staticAnalysis
  script:
    gradle authentication-and-member-microservice:checkstyleMain authentication-and-member-microservice:checkStyleTest
  allow_failure: true

PMD-authentication-and-member-microservice:
  stage: staticAnalysis
  script:
    gradle authentication-and-member-microservice:pmdMain
  allow_failure: true

test-authentication-and-member-microservice:
  stage: test
  script:
    - gradle authentication-and-member-microservice:test authentication-and-member-microservice:jacocoTestReport
    - cat authentication-and-member-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
